### ISSUE TITLE
Bump the pandas requirement to 1.0.0

### ISSUE THREAD

**Issue by billlyzhaoyh** [dkaslovsky/GraphRole#1]
Thank you so much for the package! I am wondering if it is possible to bump the requirement of pandas to be > 1.0.0. I am using the package in 1.1.0 and everything seems to be fine when I generate features and roles from a networkx undirected unweighted graph

**Comment by dkaslovsky** [comment]
Thank you for opening this issue.  This has been on my mental radar for a while now, and is absolutely something that should be done.  I'll look into it a bit more as I'd like to carefully ensure that nothing breaks and/or make changes where necessary.  I am hopeful to do this in the next week and will update if that timing changes.  Thanks again and glad you are finding the package useful!

**Comment by billlyzhaoyh** [comment]
Thank you so much for that! It will be great not to have some manual fixes in pipenv soon

**Comment by dkaslovsky** [comment]
I've bumped all dependencies to their latest versions and verified that nothing has broken, so we should be all set.  Changes are in v1.0.1 and uploaded to PyPI.  Thanks again for opening the issue and for using the package!
