### ISSUE TITLE
Algorithm with similar functions: RoleSim

### ISSUE THREAD

**Issue by BradKML** [dkaslovsky/GraphRole#4]
In https://github.com/abhishekmaha23/RoleSim-Python there is an algorithm called RoleSim that does something similar to RolX, but it relies on Role-Based-Similarity.
See https://github.com/abhishekmaha23/RoleSim-Python/blob/master/RoleSim_role_detection_v1.py for reference.

The issue is that the Object classes RecursiveFeatureExtractor and RoleExtractor might not fit directly into RoleSim, might want to ask for advice on this

**Comment by dkaslovsky** [comment]
Thanks for your note and interest in GraphRole.  I'm closing this out as there doesn't appear to be an issue or changes necessary to this repo.  Please feel free to reopen with a more specific GraphRole issue if necessary.

**Comment by BradKML** [comment]
Also checking other repos like https://github.com/kwerenda/role-mining but otherwise, will like to PR for that.
