### ISSUE TITLE
adding attribute to graph node

### ISSUE THREAD

**Issue by msm-prarthana-bataju** [dkaslovsky/GraphRole#8]
How can I add attribute to each graph node in case of BREP data?

**Comment by dkaslovsky** [comment]
Thanks for your question! While I am not familiar with BREP data, GraphRole is flexible so as to work with many graph libraries (e.g., networkx, igraph). The README contains [documentation](https://github.com/dkaslovsky/GraphRole/blob/master/README.md#graph-interfaces) for satisfying the graph interface necessary so you should be able to use GraphRole with the graph library of your choosing. Assuming that the library with which you are working supports node attributes, you should be able to make use of GraphRole's functionality as desired. Thanks again!
