### ISSUE TITLE
Graph Role for clusetring

### ISSUE THREAD

**Issue by msm-prarthana-bataju** [dkaslovsky/GraphRole#9]
Hello Dan, 
Thankyou for the code.
But could you please kindly tell me how could we use these graph role for data clustering?
How graph role works in CAD data? I extracted the features using your code but I didn't understand how its works?

Thanking you in advance.
Prarthana

**Comment by dkaslovsky** [comment]
Hi Prarthana,

Thanks for your interest! My best recommendation would be to read through the two papers cited at the bottom of this repo's [README](https://github.com/dkaslovsky/GraphRole/blob/master/README.md). The implementation here is based entirely on these papers which include discussion of various applications. In particular, you might find section 2.2 of [RolX: Structural Role Extraction & Mining in Large Graphs](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46591.pdf) useful.

Best of luck and please let me know if there's anything else I can help with!

Dan

**Comment by msm-prarthana-bataju** [comment]
Thank you for the reply Dan. I will go through it. :)
